# Reverse Proxy
version: "3"

services:
    # nginx:
    #     build: ./nginx
    #     links:
    #         - microservice1:microservice1
    #         - microservice2:microservice2
    #         - microservice3:microservice3
    #     ports:
    #         - "80:80"
    
    gateway:
        build: ./api-gateway
        links:
            - microservice1:microservice1
            - microservice2:microservice2
            - microservice3:microservice3
        environment:
            PORT: 8080
            SERVICE1_PORT: 9000
            SERVICE2_PORT: 9000
            SERVICE3_PORT: 9000
        ports:
            - "8080:8080"

    microservice1:
        build: ./services/App1
        ports:
            - "9001:9000"
        environment:
            NODE_ENV: production
            IP: 127.0.0.1
            PORT: 9000

    microservice2:
        build: ./services/App2
        ports:
            - "9002:9000"
        environment:
            NODE_ENV: production
            IP: 127.0.0.1
            PORT: 9000

    microservice3:
        build: ./services/App3
        ports:
            - "9003:9000"
        environment:
            NODE_ENV: production
            IP: 127.0.0.1
            PORT: 9000
